server:
  port: 9001

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pet-salon?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: toy
    password: toy1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true



  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
      INDENT_OUTPUT: true

# logging
#logging:
#  level:
#    org:
#      hibernate:
#        type: TRACE
#  config: config/logback-local.xml
